# Generated by Django 3.0.8 on 2020-08-01 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_answer_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='auth',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='auth',
            new_name='author',
        ),
    ]
