# Generated by Django 3.0.8 on 2020-08-07 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_question_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cate_question', to='pybo.Category'),
        ),
    ]
