# Generated by Django 3.0.8 on 2020-08-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0012_auto_20200807_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cnt',
            field=models.IntegerField(default=0),
        ),
    ]
